Tracker:AddLocations("locations/CHAINSAW RACING.json")
Tracker:AddLocations("locations/OFFICE WORK.json")
Tracker:AddLocations("locations/SUPER SAW DUCK.json")
Tracker:AddLocations("locations/TARGET MISSIONS.json")
Tracker:AddLocations("locations/TELEPORTERS.json")
Tracker:AddLocations("locations/VARIETY ZONE.json")
Tracker:AddLocations("locations/VARIETY ZONE 2.json")
Tracker:AddLocations("locations/VARIETY ZONE FINAL.json")
Tracker:AddLocations("locations/VARIETY ZONE FINAL II.json")
Tracker:AddLocations("locations/WEAPON TRAINING.json")
Tracker:AddLocations("locations/Overworld.json")
